# Generated by Django 5.1 on 2026-01-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="photo_author",
            field=models.ImageField(blank=True, null=True, upload_to="photo_author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "available"),
                    ("rented", "rented"),
                    ("sold", "sold"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
